scenarios:
  - id: "1"
    name: "Night of the Zealot"
    difficulties:
      - id: "1"
        name: "Easy"
        tokens:
          "+1": 2
          "0": 3
          "-1": 3
          "-2": 2
          "skull": 2
          "cultist": 1
          "tablet": 1
          "elder_thing": 1
      - id: "2"
        name: "Standard"
        tokens:
          "+1": 1
          "0": 2
          "-1": 3
          "-2": 2
          "-3": 1
          "-4": 1
          "skull": 2
          "cultist": 1
          "tablet": 1
          "tentacle": 1
          "elder_sign": 1
      - id: "3"
        name: "Hard"
        tokens:
          "0": 2
          "-1": 2
          "-2": 2
          "-3": 2
          "-4": 1
          "-5": 1
          "skull": 2
          "cultist": 1
          "tablet": 1
          "elder_thing": 1
      - id: "4"
        name: "Expert"
        tokens:
          "0": 1
          "-1": 2
          "-2": 2
          "-3": 2
          "-4": 2
          "-5": 1
          "-6": 1
          "skull": 2
          "cultist": 1
          "tablet": 1
          "elder_thing": 1
  
  - id: "2"
    name: "The Dunwich Legacy"
    difficulties:
      # Similar structure as above with 4 difficulty levels
      # ...
